var classes = [
    {
        "name": "ServerPlanning\\ServerPlanning",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "calculate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "ServerPlanning\\Server",
            "InvalidArgumentException",
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 43,
        "vocabulary": 14,
        "volume": 163.72,
        "difficulty": 6.4,
        "effort": 1047.78,
        "level": 0.16,
        "bugs": 0.05,
        "time": 58,
        "intelligentContent": 25.58,
        "number_operators": 11,
        "number_operands": 32,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 25,
        "loc": 54,
        "lloc": 29,
        "mi": 95.13,
        "mIwoC": 51.65,
        "commentWeight": 43.47,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 5,
        "package": "ServerPlanning\\",
        "pageRank": 0.08,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\Server",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "checkResources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateRamainingResources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "ServerPlanning\\ServerResources",
            "ServerPlanning\\VirtualMachine",
            "ServerPlanning\\VirtualMachine"
        ],
        "parents": [
            "ServerPlanning\\ServerResources"
        ],
        "lcom": 1,
        "length": 28,
        "vocabulary": 7,
        "volume": 78.61,
        "difficulty": 21.25,
        "effort": 1670.38,
        "level": 0.05,
        "bugs": 0.03,
        "time": 93,
        "intelligentContent": 3.7,
        "number_operators": 11,
        "number_operands": 17,
        "number_operators_unique": 5,
        "number_operands_unique": 2,
        "cloc": 15,
        "loc": 32,
        "lloc": 17,
        "mi": 102.98,
        "mIwoC": 59.35,
        "commentWeight": 43.63,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.43,
        "relativeSystemComplexity": 36.43,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.86,
        "totalSystemComplexity": 72.86,
        "package": "ServerPlanning\\",
        "pageRank": 0.13,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\VirtualMachine",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "ServerPlanning\\ServerResources"
        ],
        "parents": [
            "ServerPlanning\\ServerResources"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 7,
        "lloc": 4,
        "mi": 213.45,
        "mIwoC": 171,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "ServerPlanning\\",
        "pageRank": 0.23,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\ServerResources",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCpu",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCpu",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRam",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRam",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHdd",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setHdd",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 3,
        "wmc": 7,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 30,
        "vocabulary": 6,
        "volume": 77.55,
        "difficulty": 5.25,
        "effort": 407.13,
        "level": 0.19,
        "bugs": 0.03,
        "time": 23,
        "intelligentContent": 14.77,
        "number_operators": 9,
        "number_operands": 21,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 58,
        "loc": 95,
        "lloc": 37,
        "mi": 99.22,
        "mIwoC": 52.43,
        "commentWeight": 46.79,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.86,
        "relativeSystemComplexity": 3.86,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 27,
        "totalSystemComplexity": 27,
        "package": "ServerPlanning\\",
        "pageRank": 0.57,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]